version: '3.8'

services:
  typesense:
    image: typesense/typesense:0.25.2
    container_name: typesense_server
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=xyz
      - TYPESENSE_ENABLE_CORS=true
    command: '--data-dir /data --api-key=xyz --listen-port 8108 --enable-cors'
    restart: unless-stopped

  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_API_KEY=xyz
    depends_on:
      - typesense
    restart: unless-stopped

volumes:
  typesense_data:
